# Generated by Django 4.2.16 on 2026-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('stripe', 'Carte bancaire (Visa / Mastercard)'), ('cash', 'Paiement à la livraison')], default='cash', max_length=20, verbose_name='Paiement'),
        ),
    ]
