# Generated by Django 4.2.16 on 2026-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('stripe', 'Carte bancaire (Stripe)'), ('paydunya', 'PayDunya'), ('cash', 'Espèces')], max_length=20),
        ),
    ]
